### PR TITLE
Pb 2169 : Add support for kubernetes related operation on V1 cronjob

### PR DESCRIPTION
**Pull request by px-kesavan**
This PR adds support for kubernetes related operation on V1 cronjob

**What this PR does / why we need it**:  Need to support V1 apiversion for cronjobs for kube version 1.21 and above 

**Which issue(s) this PR fixes** (optional)
Closes #pb-2169

**Special notes for your reviewer**:
For complete fix its required to merge related PR in KDMP

### CODE REVIEW

**Review by prashanthpx — APPROVED** [review]

**Comment by siva-portworx** [comment]
Not sure, whether there was a real reason but when i checked previous changes, I could see that the current one they retained for V1 and added a new v1beta1.
@ram-infrac, @adityadani Any reason behind that? 
https://github.com/portworx/sched-ops/commit/d51186f75dc48cc06c03d4e9d88d20365aac32fa

**Comment by diptiranjanpx** [comment]
> Not sure, whether there was a real reason but when i checked previous changes, I could see that the current one they retained for V1 and added a new v1beta1. @ram-infrac, @adityadani Any reason behind that? [d51186f](https://github.com/portworx/sched-ops/commit/d51186f75dc48cc06c03d4e9d88d20365aac32fa)

I think for CRDs the v1 is supported from 1.16, v1beta1 was in warning phase for long time before completely getting deprecated in 1.22

**Comment by ram-infrac** [comment]
yes V1 is supported with latest k8s version lets mark old interface `CronOps` for `v1` api and introduce `v1Beta` for  deprecated apis.
Its responsibility of caller to call appropriate apis as per k8s version

**Comment by px-kesavan** [comment]
These changes have been tracked and review comments are addressed in https://github.com/portworx/sched-ops/pull/279. Closing this PR

**Pull request closed without merging**
