### PR TITLE
add utils func to register v1 crds

### PR DESCRIPTION
**Pull request by ram-infrac**

### CODE REVIEW

**Comment by piyush-nimbalkar** [comment]
Can we just use RegisterCRD function instead and also stop using the internal CustomResource object? Eventually we want everyone to use RegisterCRD with full schema while CreateCRD was meant to be deprecated.
If it's temporary, then I would say add a util in stork until then.

**Comment by ram-infrac** [comment]
yes , it will be much cleaner if we do it via stork, I was not sure other repo apart from stork& operator using sched-ops lib to register crds?

**Comment by piyush-nimbalkar** [comment]
> yes , it will be much cleaner if we do it via stork, I was not sure other repo apart from stork& operator using sched-ops lib to register crds?

Autopilot also uses it. We might have PDS use this in future.

**Comment by ram-infrac** [comment]
so should we keep this util func ?

**Comment by piyush-nimbalkar** [comment]
> so should we keep this util func ?

I think we should remove this. We are going to change autopilot too this month.

**Comment by ram-infrac** [comment]
thanks piyush

**Pull request closed without merging**
