### PR TITLE
[PA-1134] DoRetryWithTimeout - return all errors on timeout

### PR DESCRIPTION
**Pull request by tthurlapati-px**
**What this PR does / why we need it**:
fix `DoRetryWithTimeout` to collect all the errors that happen in each retry and if context deadline exceeds (timeout), those errors are also returned. Returning the errors in each retry in case of timeout helps us log them to Aetos for easier access to what happened.

> even though there is a goroutine involved, there's no need for locks to the `map` since it is **never** accessed concurrently.

Closes #PA-1134

### CODE REVIEW

**Comment by tthurlapati-px** [comment]
**Special notes for your reviewer**:
I wrote a dummy testcase in Torpedo and checked using this branch of sched-ops, I checked if it was returning all error properly by logging them to Aetos. The Aetos run:
https://aetos.pwx.purestorage.com/resultSet/testSetID/211145
The specific testcase:
https://aetos.pwx.purestorage.com/resultSet/testSetID/211145/testCaseID/1112422

**The dummy code I used:**

```go
// This testcase verifies basic backup rule,backup location, cloud setting
var _ = Describe("{BasicBackupCreation2}", func() {
	JustBeforeEach(func() {
		StartTorpedoTest("Backup: BasicBackupCreation", "Deploying backup", nil, 0)
	})

	It("Basic Backup Creation", func() {
		i := 0
		f := func() (interface{}, bool, error) {
			i += 1
			return nil, true, fmt.Errorf("cluster state is [%d]. Waiting to become complete", i)
		}
		_, err := task.DoRetryWithTimeout(f, time.Second*10, time.Second)
		log.FailOnError(err, "faille")
	})

	JustAfterEach(func() {
		defer EndPxBackupTorpedoTest(nil)
	})
})
```


**The logs for the testcase look like this:**

```
------------------------------
{BasicBackupCreation2} 
  Basic Backup Creation
  /root/torpedo/tests/backup/backup_test.go:341
2023-06-01 04:30:29 +0000:[INFO] [{BasicBackupCreation2}] Log Dir: /root/torpedo/Backup: BasicBackupCreation.log
INFO[2023-06-01 04:30:29] =======Test Start=======                     
INFO[2023-06-01 04:30:29] #Test: Backup: BasicBackupCreation           
INFO[2023-06-01 04:30:29] #Description: Deploying backup               
INFO[2023-06-01 04:30:29] ------------------------                     
INFO[2023-06-01 04:30:29] Running test from file torpedo/tests/common.go, module: Backup: BasicBackupCreation 
INFO[2023-06-01 04:30:29] Dashboard Testase URL : https://aetos.pwx.purestorage.com/resultSet/testSetID/211145/testCaseID/1112422 
2023/06/01 04:30:29 DoRetryWithTimeout - Error: {cluster state is [1]. Waiting to become complete}, Next try in [1s], timeout [10s]
2023/06/01 04:30:30 DoRetryWithTimeout - Error: {cluster state is [2]. Waiting to become complete}, Next try in [1s], timeout [10s]
2023/06/01 04:30:31 DoRetryWithTimeout - Error: {cluster state is [3]. Waiting to become complete}, Next try in [1s], timeout [10s]
2023/06/01 04:30:32 DoRetryWithTimeout - Error: {cluster state is [4]. Waiting to become complete}, Next try in [1s], timeout [10s]
2023/06/01 04:30:33 DoRetryWithTimeout - Error: {cluster state is [5]. Waiting to become complete}, Next try in [1s], timeout [10s]
2023/06/01 04:30:34 DoRetryWithTimeout - Error: {cluster state is [6]. Waiting to become complete}, Next try in [1s], timeout [10s]
2023/06/01 04:30:35 DoRetryWithTimeout - Error: {cluster state is [7]. Waiting to become complete}, Next try in [1s], timeout [10s]
2023/06/01 04:30:36 DoRetryWithTimeout - Error: {cluster state is [8]. Waiting to become complete}, Next try in [1s], timeout [10s]
2023/06/01 04:30:37 DoRetryWithTimeout - Error: {cluster state is [9]. Waiting to become complete}, Next try in [1s], timeout [10s]
2023/06/01 04:30:38 DoRetryWithTimeout - Error: {cluster state is [10]. Waiting to become complete}, Next try in [1s], timeout [10s]
2023-06-01 04:30:39 +0000:[ERROR] [{BasicBackupCreation2}] [backup.glob..func68.2:#348] - faille. Err: timed out performing task., Error was: DoRetryWithTimeout timed out. Errors generated in retries: {cluster state is [1]. Waiting to become complete}
{cluster state is [2]. Waiting to become complete}
{cluster state is [3]. Waiting to become complete}
{cluster state is [4]. Waiting to become complete}
{cluster state is [5]. Waiting to become complete}
{cluster state is [6]. Waiting to become complete}
{cluster state is [7]. Waiting to become complete}
{cluster state is [8]. Waiting to become complete}
{cluster state is [9]. Waiting to become complete}
{cluster state is [10]. Waiting to become complete}
INFO[2023-06-01 04:30:39] Verifying : Description : Test completed successfully ? 
ERRO[2023-06-01 04:30:39] Actual:TEST-ERROR, Expected: PASS   
INFO[2023-06-01 04:30:39] --------Test End--------                     
INFO[2023-06-01 04:30:39] #Test: Backup: BasicBackupCreation           
INFO[2023-06-01 04:30:39] #Description: Deploying backup               
INFO[2023-06-01 04:30:39] #Dashboard Testcase URL: https://aetos.pwx.purestorage.com/resultSet/testSetID/211145/testCaseID/1112422 
INFO[2023-06-01 04:30:39] ========================                     
```

**At the end, ginkgo shows the error as:**

```
• Failure [13.827 seconds]
{BasicBackupCreation2}
/root/torpedo/tests/backup/backup_test.go:336
  Basic Backup Creation [It]
  /root/torpedo/tests/backup/backup_test.go:341

  Unexpected error:
      <*task.ErrTimedOut | 0xc00167e1a0>: {
          Reason: "DoRetryWithTimeout timed out. Errors generated in retries: {cluster state is [1]. Waiting to become complete}\n{cluster state is [2]. Waiting to become complete}\n{cluster state is [3]. Waiting to become complete}\n{cluster state is [4]. Waiting to become complete}\n{cluster state is [5]. Waiting to become complete}\n{cluster state is [6]. Waiting to become complete}\n{cluster state is [7]. Waiting to become complete}\n{cluster state is [8]. Waiting to become complete}\n{cluster state is [9]. Waiting to become complete}\n{cluster state is [10]. Waiting to become complete}",
      }
      timed out performing task., Error was: DoRetryWithTimeout timed out. Errors generated in retries: {cluster state is [1]. Waiting to become complete}
      {cluster state is [2]. Waiting to become complete}
      {cluster state is [3]. Waiting to become complete}
      {cluster state is [4]. Waiting to become complete}
      {cluster state is [5]. Waiting to become complete}
      {cluster state is [6]. Waiting to become complete}
      {cluster state is [7]. Waiting to become complete}
      {cluster state is [8]. Waiting to become complete}
      {cluster state is [9]. Waiting to become complete}
      {cluster state is [10]. Waiting to become complete}
  occurred

  /root/torpedo/pkg/log/log.go:334
```

**Review by nikolaypopov — APPROVED** [review]
LGTM, thanks for making this change, it does help a lot in terms of debugging, seeing context deadline is not helpful at all. Please build a torpedo image with this change and run at least one job that uses it and make sure it works before merging

**Comment by tthurlapati-px** [comment]
Great, I'm glad! Just to confirm, do you want me to build the Torpedo image with the modified sched-ops package **after** I merge this PR into `master` in sched-ops, or before I merge this PR?

**Comment by tthurlapati-px** [comment]
I used BYOC pipeline to create image and run tests:
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/1556/
https://aetos.pwx.purestorage.com/resultSet/testSetID/212518

I executed 2 testcases, 1 which should succeed and another that should fail due to an issue with my cluster setup. This way, I was able to test if the logging is done on **timeout**.

Things look good.

**Pull request merged**
